/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { clientsClaim } from 'workbox-core';

declare let self: ServiceWorkerGlobalScope;

// Take control of all pages immediately
self.skipWaiting();
clientsClaim();

// Precache all assets generated by Vite build process (injected by workbox)
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old / outdated cached files from previous versions
cleanupOutdatedCaches();

// Single Page Application Navigation handler
// Serves precached index.html for all page navigation requests
const navigationHandler = createHandlerBoundToURL('/index.html');
const navigationRoute = new NavigationRoute(navigationHandler, {
  denylist: [/^\/api\//, /^\/sw\.js/, /^\/manifest\.webmanifest/, /^\/registerSW\.js/],
});
registerRoute(navigationRoute);

// Cache Google Fonts stylesheets with StaleWhileRevalidate strategy
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Cache Google Fonts webfont files with CacheFirst strategy (1 year)
registerRoute(
  /^https:\/\/fonts\.gstatic\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 60 * 60 * 24 * 365,
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Cache static images with StaleWhileRevalidate strategy (30 days)
registerRoute(
  /\.(?:png|jpg|jpeg|svg|gif|webp|ico)$/i,
  new StaleWhileRevalidate({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 60 * 60 * 24 * 30,
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Standard Service Worker lifecycle event listeners
// Explicitly provided for PWABuilder and PWA engine validation
self.addEventListener('install', (event: ExtendableEvent) => {
  // Activate worker immediately without waiting for existing clients
  self.skipWaiting();
});

self.addEventListener('activate', (event: ExtendableEvent) => {
  event.waitUntil(
    Promise.all([
      self.clients.claim(),
      // Ensure stale caches are cleaned up
      caches.keys().then((cacheNames) => {
        return Promise.all(
          cacheNames
            .filter((cacheName) => {
              // Delete any unversioned or obsolete legacy caches
              return cacheName.startsWith('bantay-kuryente-old-');
            })
            .map((cacheName) => caches.delete(cacheName))
        );
      }),
    ])
  );
});

// Fallback fetch listener for additional resilience & PWABuilder recognition
self.addEventListener('fetch', (event: FetchEvent) => {
  // Let workbox handle registered routes; for HTML navigations that fail, fallback to offline.html
  if (event.request.mode === 'navigate') {
    event.respondWith(
      fetch(event.request).catch(async () => {
        const cachedResponse = await caches.match(event.request);
        if (cachedResponse) {
          return cachedResponse;
        }
        const fallback = await caches.match('/offline.html');
        if (fallback) {
          return fallback;
        }
        return caches.match('/index.html') as Promise<Response>;
      })
    );
  }
});

// Listen for custom messages from clients (e.g. SKIP_WAITING)
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
